<h3 align="center">Codebasics ML Course: K Fold Cross Validation</h3>

We will generate a synthetic dataset

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_features=10, 
    n_samples=1000, 
    n_informative=8,
    n_redundant=2,
    n_repeated=0,
    n_classes=2, 
    random_state=42
)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [2]:
from sklearn.metrics import classification_report

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.73      0.65      0.69       130
           1       0.66      0.74      0.70       120

    accuracy                           0.70       250
   macro avg       0.70      0.70      0.70       250
weighted avg       0.70      0.70      0.70       250



In [3]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_index, test_index in kf.split([50,60,70,80,90]):
    print(train_index, test_index)

[0 2 3 4] [1]
[0 1 2 3] [4]
[0 1 3 4] [2]
[1 2 3 4] [0]
[0 1 2 4] [3]


In [4]:
model = LogisticRegression()

for train_index, test_index in kf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]  
    model.fit(X_train, y_train)
    print(model.score(X_test, y_test))

0.675
0.715
0.72
0.645
0.72


### Cross validation on Logistic Regression

In [5]:
from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(), X, y, cv=kf, scoring="accuracy")

array([0.675, 0.715, 0.72 , 0.645, 0.72 ])

### Cross validation on Decision Tree

In [6]:
from sklearn.tree import DecisionTreeClassifier
cross_val_score(DecisionTreeClassifier(), X, y, cv=kf, scoring="accuracy")

array([0.7  , 0.82 , 0.805, 0.805, 0.8  ])

### Cross validation on Random Forest

In [7]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(n_estimators=10), X, y, cv=kf, scoring="accuracy")

array([0.785, 0.83 , 0.855, 0.88 , 0.885])

### Cross validation to evaluate same model with different parameters

Random Forest on 20 Trees

In [8]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(n_estimators=20), X, y, cv=kf, scoring="accuracy")

array([0.84 , 0.855, 0.845, 0.89 , 0.885])

Random Forest on 30 Trees

In [9]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(n_estimators=30), X, y, cv=kf, scoring="accuracy")

array([0.86 , 0.895, 0.865, 0.905, 0.895])

### Using cross_validate to evaluate multiple metrics

In [10]:
from sklearn.model_selection import cross_validate

cross_validate(LogisticRegression(), X, y, cv=kf, scoring=["accuracy", "roc_auc"])

{'fit_time': array([0.00500417, 0.01547098, 0.00504351, 0.00575161, 0.01002431]),
 'score_time': array([0.00299907, 0.00220251, 0.00241065, 0.00200105, 0.00199986]),
 'test_accuracy': array([0.675, 0.715, 0.72 , 0.645, 0.72 ]),
 'test_roc_auc': array([0.73916098, 0.77691076, 0.79251701, 0.74919872, 0.77579285])}